
package sendmail;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendMailInterface", targetNamespace = "http://sendmail/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendMailInterface {


    /**
     * 
     * @param payload
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://sendmail/", className = "sendmail.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://sendmail/", className = "sendmail.SendEmailResponse")
    public boolean sendEmail(
        @WebParam(name = "url", targetNamespace = "")
        String url,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateEmailAddress", targetNamespace = "http://sendmail/", className = "sendmail.ValidateEmailAddress")
    @ResponseWrapper(localName = "validateEmailAddressResponse", targetNamespace = "http://sendmail/", className = "sendmail.ValidateEmailAddressResponse")
    public boolean validateEmailAddress(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param payload
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailBatch", targetNamespace = "http://sendmail/", className = "sendmail.SendEmailBatch")
    @ResponseWrapper(localName = "sendEmailBatchResponse", targetNamespace = "http://sendmail/", className = "sendmail.SendEmailBatchResponse")
    public boolean sendEmailBatch(
        @WebParam(name = "url", targetNamespace = "")
        List<String> url,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

}
