
package sendmail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendMailInterface", targetNamespace = "http://sendmail/", wsdlLocation = "http://localhost:8888/Webservice?wsdl")
public class SendMailInterface_Service
    extends Service
{

    private final static URL SENDMAILINTERFACE_WSDL_LOCATION;
    private final static WebServiceException SENDMAILINTERFACE_EXCEPTION;
    private final static QName SENDMAILINTERFACE_QNAME = new QName("http://sendmail/", "SendMailInterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/Webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMAILINTERFACE_WSDL_LOCATION = url;
        SENDMAILINTERFACE_EXCEPTION = e;
    }

    public SendMailInterface_Service() {
        super(__getWsdlLocation(), SENDMAILINTERFACE_QNAME);
    }

    public SendMailInterface_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMAILINTERFACE_QNAME, features);
    }

    public SendMailInterface_Service(URL wsdlLocation) {
        super(wsdlLocation, SENDMAILINTERFACE_QNAME);
    }

    public SendMailInterface_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMAILINTERFACE_QNAME, features);
    }

    public SendMailInterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMailInterface_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMailInterface
     */
    @WebEndpoint(name = "SendMailPort")
    public SendMailInterface getSendMailPort() {
        return super.getPort(new QName("http://sendmail/", "SendMailPort"), SendMailInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMailInterface
     */
    @WebEndpoint(name = "SendMailPort")
    public SendMailInterface getSendMailPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sendmail/", "SendMailPort"), SendMailInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMAILINTERFACE_EXCEPTION!= null) {
            throw SENDMAILINTERFACE_EXCEPTION;
        }
        return SENDMAILINTERFACE_WSDL_LOCATION;
    }

}
